name: Docker CI/CD Pipelines

env:
    TAG : "egorba/getting-started:latest"
    DATABASE_NAME: ${{secrets.DATABASE_NAME}}
    DATABASE_COLUMN: "dat"
    DATABASE_USER: "osmvcnou"
    DATABASE_PASSWORD: "rdFDPWZpoW2RrvLno9qEDwVMhruzEZ-S"
    DATABASE_HOST: "lallah.db.elephantsql.com"
    DATABASE_N: "osmvcnou"

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  Pipline:

    runs-on: ubuntu-latest

    steps:
    
    - name: Test env vars for python
      run: echo $DATABASE_NAME
      
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag $TAG
      
    - uses: actions/checkout@v3
    - name: Push the Docker image
      run: docker push $TAG
      
    - uses: actions/checkout@v3
    - name: Build the Docker Compose
      run: |
          touch .env
          echo DATABASE_NAME="${{ secrets.DATABASE_NAME }}" >> .env
          docker-compose build
      
    - uses: actions/checkout@v3
    - name: Run the Docker Compose
      run: |
          touch .env
          echo DATABASE_NAME="${{ secrets.DATABASE_NAME }}" >> .env
          docker-compose up
    
