name: Docker CI/CD Pipelines

env:
    TAG : "egorba/getting-started:latest"
    DATABASE_NAME: "penguins"
    DATABASE_COLUMN: "dat"
    DATABASE_USER: "osmvcnou"
    DATABASE_PASSWORD: "rdFDPWZpoW2RrvLno9qEDwVMhruzEZ-S"
    DATABASE_HOST: "lallah.db.elephantsql.com"
    DATABASE_N: "osmvcnou"

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  Pipline:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Login to DockerHub
      run: docker login -u ${{secrets.DOCKERHUB_USERNAME}} -p ${{secrets.DOCKERHUB_TOKEN}}
      
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag $TAG
      
    - uses: actions/checkout@v3
    - name: Push the Docker image
      run: docker push $TAG
      
    - uses: actions/checkout@v3
    - name: Build the Docker Compose
      run: docker-compose build
      
    - uses: actions/checkout@v3
    - name: Run the Docker Compose
      run: docker-compose up
    
